### ISSUE TITLE
Suggest: load static images with jsdelivr

### ISSUE THREAD

**Issue by vensing** [ryan4yin/ryan4yin.space#1]
It may be possible to use the jsdelivr CDN to speed up the loading of static images : ) 
Set up a repository and then load the static resources using the JsDelivr CDN service.

**Comment by ryan4yin** [comment]
@vensing Appreciate further details :smile: so how to upload those static images to jsdelivr CDN via github actions?

**Comment by vensing** [comment]
Just create a github repo to save static resources，and then push your images or other resources to the repo. So you can use format load images like that https://can.jsdelivr.net/gh/username/reponame@version/folder/sample.png

**Comment by ryan4yin** [comment]
@vensing got it, thanks~

**Comment by vensing** [comment]
More detailed usage：https://github.com/jsdelivr/jsdelivr#github

**Comment by ryan4yin** [comment]
@vensing jsdelivr cdn for js/css can be enabled by default through theme's configuration:

```toml
  # LoveIt 更改 | 0.2.7 第三方库文件的 CDN 设置
  [params.cdn]
    # CDN 数据文件名称, 默认不启用
    # ("jsdelivr.yml")
    # 位于 "themes/LoveIt/assets/data/cdn/" 目录
    # 可以在你的项目下相同路径存放你自己的数据文件:
    # "assets/data/cdn/"
    data = "jsdelivr.yml"
```

and I'll try to speed up the static images using the method you provided.
